accounts/urls.py
from django.urls import path
from . import views



app_name="accounts"
urlpatterns = [
    path('', views.login_user, name="login"),
    path('logout/', views.logout_user, name='logout')

    

    
]

polls/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name="polls"
urlpatterns = [
    path('list/', views.polls_list, name="list")

]

project/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

urlpatterns = [
  
  path('admin/', admin.site.urls),
  path('home/', views.home, name='home'),
  path('', include('accounts.urls', namespace="accounts")),
  path('polls/', include('polls.urls', namespace='polls'))
  

]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.
#Aqui tem a configuração do modelo de Polls
class Poll(models.Model):
    text = models.CharField(max_length=255)
    pub_date = models.DateField()

    def __str__(self):
        return self.text

class Choice(models.Model):
    question = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{} - {}".format(self.question.text[:25], self.choice_text[:25])

accounts/views.py
#from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('home'))
        else:
            messages.error(request, 'Usuário errado ou senha')
            #return HttpResponseRedirect(reverse('homepage'))
   
    return render(request, 'accounts/login.html')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def acc(request):
    context = {}
    return render(request, 'login.html', context)

polls/views.py
from django.shortcuts import render

from .models import Poll
# Create your views here.
def polls_list(request):


#Renderiza a poll_list.html que lista todas as polls disponiveis .
    polls = Poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/polls_list.html', context)

project/views.py
#from django.http import HttpResponseRedirect
#from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages


# Create your views here.


def home(request):
    context = {}
    return render(request, 'home.html', context)
    
def accounts(request):
    return render(request, 'accounts/login.html')


   
    
    

accounts/templates/accounts/home.html
{% extends 'base.html'%}

        {% block head %}
        <title>Homepage</title>
        {% endblock %}}
    <h1>test</h1>
        {% block body  %}
        <h1>Home</h1>
        {%  endblock %}  

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
    {% block head %}
  <meta charset="UTF-8">
  <title>A Pen by  Lucas</title>
  

  {% endblock %}
</head>
{% block content %} 
  
  <body>
  <body style="background-color: #24292f;">
    <div class="py-fluid w-100 p-4 h-75">
      <div class="container-fluid TEX">
        <div class="row">
          <div class="col-md-6"></div>
          <div class="col-md-6">
            <h1 class="">Crie sua conta para compartilhar...</h1>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mr-auto">
            <p class="lead">Compartilhe o que quiser, com quiser!&nbsp;
              <br>
            </p>
         <p class="lead">Prezamos o poder da comunicação, valorizamos as interações humanas sem censura.&nbsp;
              <br>Crie conteúdo, compartilhe, debata e colecione amigos em nossa plataforma.&nbsp;
              <br> </p>
          </div>
          <div class="col-md-6">
            <form class="">
              <div class="form-group">
                <label>Endereço de email
                  <br>
                </label>
                <input type="email" class="form-control" placeholder="Insira seu email">{% csrf_token %}
                <small class="form-text text-muted">Nossa equipe não irá compartilhar seus dados com ninguém.&nbsp;</small>
              </div>
              <div class="form-group">
                <label>Senha
                  <br>
                </label>
                <input type="password" class="form-control" placeholder="Senha"> </div>
              <button type="submit" class="btn">Cadastre-se</button>
            </form>
          </div>
        </div>
      </div>
      <hr>
    </div>
    <div class="text-white h-25 mr-auto py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="list-inline text-center">
              <li class="list-inline-item">Termo de compromisso</li>
              <li class="list-inline-item">Privacidade</li>
              <li class="list-inline-item">Sobre nossa empresa</li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mt-3 text-center">
            <p>© Copyright 2018 - GADO DEMAIS.</p>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
    
    
  
  
  </html>
  
  
  
{% endblock %}  
</body>

</html>

polls/templates/polls/polls_list.html
<!DOCKTYPE html>
{% extends 'base.html' %}


{% block head %}  

{% endblock %}  



{% block content %}    
<div class="container">
   
    <h1>Bem vindo a Poll List!</h1>
    <ul>
     {% for poll in polls %}
        <li>{{ poll }}</li>
    <ul>
        {% for choice in poll.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
    {% endfor %}
    </ul>
</div>    
        
        
{% endblock %}

templates/base.html
<html>
{% load static %}
    <head>
         
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <link rel='stylesheet' type='text/css' href="{% static 'css/home_styles.css' %}">
        
        {% block head %}          
   
        
        
        {%endblock%}
  
    </head>
    
    <body>
     {% include "includes/navbar.html" %}
       {% block content %}
         <h1>Essa tag controla o Body</h1>
          

        {% endblock %}   
    
        
        
        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
    {% block head %}
  <meta charset="UTF-8">
  <title>GADO DEMAIS</title>
  

  {% endblock %}
  
</head>
{% block content %} 
<body style="background-color: #24292f;"></body>
<h1>HOME PAGE PARA O GADO DO WILLIAM VER</h1>

  </body>
    
    
  
  
  </html>
  
  
  
{% endblock %}  
</body>

</html>

templates/home_old.html
{% extends 'base.html' %}
{% load static %}
<head>
{% block head %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
 
{% endblock %}

 </head>    
 {% block content %}   

        <body style="background-color: #151515;">          
            <div class="py-fluid w-100 p-4 h-75">
              <div class="container-fluid TEX">
                <div class="row">
                  <div class="col-md-6"></div>
                  <div class="col-md-6">
                    <h1 class="">Crie sua conta para compartilhar...</h1>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 mr-auto">
                    <p class="lead">Compartilhe o que quiser, com quiser!&nbsp;
                      <br>
                    </p>
                    <p class="lead">Prezamos o poder da comunicação, valorizamos as interações humanas sem censura. Crie conteúdo, compartilhe, debata e colecione amigos em nossa plataforma.&nbsp;
                      <br>
                    </p>
                  </div>
                  <div class="col-md-6">
                    <form action="" method="post">{% csrf_token %}
                      <div class="form-group">
                        <label>Endereço de email
                          <br>
                        </label>
                        <input type="text" class="form-control" name="username" placeholder="Insira seu usuário">
                        <small class="form-text text-muted">Nossa equipe não irá compartilhar seus dados com ninguém.&nbsp;</small>
                      </div>
                      <div class="form-group">
                        <label>Senha
                          <br>
                        </label>
                        <input type="password" class="form-control" name="password" placeholder="Senha"> </div>
                      <button type="submit" class="btn btn-primary">Logar-se</button>
                    </form>
                  </div>
                </div>
              </div>
              <hr>
            </div>
            <div class="text-white h-25 mr-auto py-5">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <ul class="list-inline text-center">
                      <li class="list-inline-item">Termo de compromisso</li>
                      <li class="list-inline-item">Privacidade</li>
                      <li class="list-inline-item">Sobre nossa empresa</li>
                    </ul>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12 mt-3 text-center">
                    <p>© Copyright 2018 - GADO DEMAIS.</p>
                  </div>
                </div>
              </div>
            </div>
          {% endblock %}  
      </body>

 

templates/homepage.html
<H1>Olá Pessoal</H1>

templates/includes/navbar.html
<nav style="background-color: #718760;" class="navbar navbar-expand-md navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end"   id="navbar2SupportedContent">
       {% if messages %}
          <ul class="messages">
            {% for messages in messages %}
            <li>{% if messages.tags %} class="{{ messages.tags }}" {% endif %}> {{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
          <form action="" method="post" form class="form-inline my-2 my-lg-0">{% csrf_token %}
          <div class="form-group">
            <label for="username"></label>
            <input type="text" class="form-control form-control-sm p-1 mx-2" name="username" placeholder="Usuário">
          </div>
          <label for="password"></label>
          <input type="password" class="form-control mx-2 form-control-sm p-1" name="password" placeholder="Senha">
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            {% if request.user.is_authenticated %}
           
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            
            {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
            
            
           <button class="btn my-sm-0 btn-sm mx-2 active px-1" type="submit" >Entrar</button>
            {% endif %}
         
            <a class="nav-item nav-link" href="{% url 'home' %}">Home<span class="sr_only"></span></a>
               <a class="nav-item nav-link" href="{% url 'polls:list' %}">Teste<span class="sr_only"></span></a>
        </div>
      </form>
    </div>
  </div>
</nav>
               
         